##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1998 by Lutz Sammer
##
##	$Id: Makefile,v 1.1 1998/12/23 05:38:06 root Exp $
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE	= network
OBJS	= network.$(OE)

include $(TOPDIR)/Common.mk
