##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1999 by Lutz Sammer
##
##	$Id: Makefile,v 1.2 1999/05/18 20:05:48 root Exp $
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE  = unit

OBJS	= ut_table.$(OE) unittype.$(OE) ccl_unittype.$(OE) \
	  ub_table.$(OE) button.$(OE) ccl_button.$(OE)

include $(TOPDIR)/Common.mk
