##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1999 by Lutz Sammer
##
##	$Id: Makefile,v 1.2 1999/12/03 09:18:25 root Exp $
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE  = pathfinder

OBJS	= pathfinder.$(OE) astar.$(OE)

include $(TOPDIR)/Common.mk
