##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1998 by Lutz Sammer
##
##	$Id: Makefile,v 1.7 1999/11/26 17:42:30 root Exp $
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE	= video
OBJS	= new_video.$(OE) sdl.$(OE) new_X11.$(OE) X11.$(OE) video.$(OE) \
	  graphic.$(OE) png.$(OE) svgalib.$(OE)

include $(TOPDIR)/Common.mk
