##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1999 by Lutz Sammer
##
##	$Id: Makefile,v 1.5 1999/06/04 21:07:15 root Exp $
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE  = map

OBJS	= map.$(OE) map_draw.$(OE) ccl_map.$(OE) \
	  map_fog.$(OE) map_rock.$(OE) map_wood.$(OE) map_wall.$(OE) \
	  minimap.$(OE) tileset.$(OE)

include $(TOPDIR)/Common.mk
