##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1998,1999 by Lutz Sammer
##
##	$Id: Makefile,v 1.22 1999/11/26 17:42:24 root Exp $
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE  = clone

OBJS	= clone.$(OE) unit.$(OE) unit_draw.$(OE) unitcache.$(OE) \
	  unit_find.$(OE) missile.$(OE) construct.$(OE)\
          player.$(OE) pud.$(OE) image.$(OE) cursor.$(OE) \
	  ccl.$(OE) interface.$(OE) \
	  upgrade.$(OE) font.$(OE) \
	  mainloop.$(OE) goal.$(OE) selection.$(OE) groups.$(OE)

include $(TOPDIR)/Common.mk
