##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1998 by Lutz Sammer
##
##	$Id: Makefile,v 1.7 2000/01/16 23:38:08 root Exp $
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

##
## USER INTERFACE
##
## TODO: move here all user-interface-related files
##

MODULE	= ui
OBJS	= mouse.$(OE) button_table.$(OE) botpanel.$(OE) mainscr.$(OE) \
	  icons.$(OE) ui.$(OE) ccl_ui.$(OE) image.$(OE) menus.$(OE)

include $(TOPDIR)/Common.mk
