##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1998 by Lutz Sammer
##
##	$Id: Makefile,v 1.2 1998/12/06 08:51:18 root Exp $
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE  = ai

OBJS	= ai.$(OE)

include $(TOPDIR)/Common.mk
