##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1998 by Lutz Sammer
##
##	$Id: Makefile,v 1.11 1999/05/29 21:32:54 root Exp $
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE  = action

OBJS	= command.$(OE) actions.$(OE) action_die.$(OE) action_patrol.$(OE) \
	action_still.$(OE) action_move.$(OE) action_attack.$(OE) \
	action_board.$(OE) action_unload.$(OE) action_repair.$(OE) \
	action_harvest.$(OE) action_minegold.$(OE) action_hauloil.$(OE) \
	action_returngoods.$(OE) action_research.$(OE) action_demolish.$(OE) \
	action_build.$(OE) action_train.$(OE) action_upgradeto.$(OE)  

include $(TOPDIR)/Common.mk
